try {
    let a = 42;
} catch (er) {
    let b = "fail";
} finally {
    let c = "finally";
}
